services:
  tempo:
    image: grafana/tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "3200:3200" # tempo
      - "9095:9095" # tempo

  pyroscope:
    image: grafana/pyroscope
    ports:
      - "4040:4040"

  grafana:
    image: grafana/grafana:main
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "43000:3000"
    depends_on:
      - tempo
